### ISSUE TITLE
lightGallery - v1.3.9

### ISSUE THREAD

**Issue by bartmika** [andyklimczak/djangocms-light-gallery#1]
Can we upgrade the plugin to support the latest version of `lightGallery` ?

https://github.com/sachinchoolur/lightGallery/releases

**Comment by rodolfomartinez** [comment]
+1

**Comment by andyklimczak** [comment]
Yeah, definitely. The only trick is matching the licenses. But shouldn't be an issue from my end.

**Comment by andyklimczak** [comment]
Updated to 1.4.0. Let me know if you find any issues !~
