### ISSUE TITLE
Cannot choose images to be implemented in front-end editor

### ISSUE THREAD

**Issue by lukyncze** [andyklimczak/djangocms-light-gallery#14]
Hello, I´ve installed this plugin and I cannot somehow choose from my images (or choose whole folder) that which I want to implement on my website. Any ideas how to fix this problem? Thank you

![image](https://user-images.githubusercontent.com/36028726/97087098-d0f22d80-1627-11eb-911f-010c730a2990.png)

**Comment by andyklimczak** [comment]
Hey, which versions of djangocms, django, and python are you using?

**Comment by lukyncze** [comment]
Djangocms - latest 3.7.4
Django - 3.0.10
Python - 3.8.5

**Comment by lukyncze** [comment]
Hey, I am just an idiot. I did not realized that you must click on the left of the folder. Everything is perfectly functional. Thank you
