### ISSUE TITLE
Django-CMS Marketplace Add-on

### ISSUE THREAD

**Issue by bartmika** [andyklimczak/djangocms-light-gallery#2]
This is a great plugin that I recently discovered and I would love to see it in the `Django-CMS marketplace` so other developers can use it. 

The store is located here:
https://marketplace.django-cms.org/en/addons/

I don't think it's too much work to set it up either. Here is the link to do it:
http://support.divio.com/marketplace/addons/how-to-publish-addons-on-the-django-cms-marketplace

**Comment by andyklimczak** [comment]
Thanks! I didn't know about this, I will look into adding it

**Comment by andyklimczak** [comment]
Added it to the marketplace here: https://marketplace.django-cms.org/en/addons/browse/djangocms-light-gallery/

Thanks for suggesting this !

**Comment by bartmika** [comment]
Thank you!

**Comment by andyklimczak** [comment]
Let me know if you find any issues with it, of course
