### ISSUE TITLE
UX improvements - reduce the complexity of the plugin configuration for editors

### ISSUE THREAD

**Issue by viktor-yunenko** [andyklimczak/djangocms-light-gallery#9]
It's great that we have collapsible elements already that hide most of the scary settings, I would like to propose to iterate over this idea by moving up the most user-friendly settings.

It's all organized rather good, perhaps the only thing we need to change is the order. As a user I would open the collapsed elements from top to bottom, and when I open the Core section my first thought might be "*this is for developers, no point in looking at the sections below*" :) . Perhaps we can rearrange them as following:
- Toolbar on fullscreen
    - enable actual size button
    - enable zoom buttons
    - enable fullscreen button
- Social networks sharing
- Gallery Thumbnails
- Everything else

**Comment by andyklimczak** [comment]
Sounds good, I agree. I appreciate the feedback from you using the plugin!

The structure I had was following the structure from the [light gallery docs](https://sachinchoolur.github.io/lightGallery/docs/api.html#passing-options), so if you were looking there you could find it easily in the plugin. But I do think this is better.

Thanks!
